name: build-image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SOURCE_DIRECTORY: './src/APIMetrics'
  IMAGE_DOCKERHUB: 'api-fake-saudcao'

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build de imagem
      run: |
        cd ${{ env.SOURCE_DIRECTORY }}
        podman build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_DOCKERHUB }}:latest      
    - name: Login no Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | podman login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin docker.io
    - name: Geração de tag com número do Build e Push no Docker Hub
      run: |
        podman tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_DOCKERHUB }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_DOCKERHUB }}:$GITHUB_RUN_NUMBER
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_DOCKERHUB }}"
        for TAG in $(podman images --format "{{.Tag}}" ${IMAGE_NAME}); do
          podman push ${IMAGE_NAME}:${TAG}
        done
    - name: Exibir imagens no ambiente
      run: podman images
